/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppAlertKind = "CHANGE_PCT_ABOVE" | "CHANGE_PCT_BELOW" | "CORPORATE_EVENT" | "INDICATOR" | "IPO_EVENT" | "IV_ABOVE" | "IV_BELOW" | "NEW_52W_HIGH" | "NEW_52W_LOW" | "OI_CHANGE_PCT_ABOVE" | "PRICE_ABOVE" | "PRICE_BELOW" | "SCREEN_MATCH" | "VOLUME_ABOVE";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type CorpPeriodType = "FY" | "H" | "Q";

export type CorpStatementType = "BS" | "CF" | "PL";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IpoStatus = "ALLOTTED" | "CLOSED" | "DRHP_FILED" | "LISTED" | "OPEN" | "UPCOMING" | "WITHDRAWN";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LabRunStatus = "CANCELLED" | "FAILED" | "QUEUED" | "RUNNING" | "SUCCEEDED";

export type Numeric = ColumnType<number, number | string, number | string>;

export type RefCorpActionType = "BONUS" | "BUYBACK" | "DELISTING" | "DEMERGER" | "DIVIDEND" | "FACE_VALUE_CHANGE" | "INTEREST_PAYMENT" | "MERGER" | "NAME_CHANGE" | "OTHER" | "REDEMPTION" | "RIGHTS" | "SPLIT" | "SUSPENSION" | "SYMBOL_CHANGE";

export type RefInstrumentKind = "FUTURE" | "INDEX" | "LISTING" | "OPTION" | "SPOT";

export type RefInstrumentStatus = "ACTIVE" | "DELISTED" | "EXPIRED" | "SUSPENDED";

export type RefOptionType = "CE" | "PE";

export type RefSecurityType = "CERT_OF_DEPOSIT" | "COMMERCIAL_PAPER" | "CORPORATE_BOND" | "EQUITY" | "ETF" | "GSEC" | "INVIT" | "NCD" | "PREFERENCE" | "REIT" | "RIGHTS_ENTITLEMENT" | "SDL" | "SGB" | "TBILL";

export type RefSegment = "CASH" | "COMMODITY_DERIV" | "CURRENCY_DERIV" | "DEBT" | "EQ_DERIV" | "INDEX";

export type RefSessionKind = "BLOCK_DEAL" | "CLOSING_AUCTION" | "MUHURAT" | "NORMAL" | "POST_CLOSE" | "PRE_OPEN" | "SPECIAL";

export type RefSettlementType = "CASH" | "INTO_FUTURES" | "PHYSICAL";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppAlert {
  channels: Generated<string[]>;
  cooldown: Generated<string>;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  instrument_id: number | null;
  ipo_issue_id: number | null;
  kind: AppAlertKind;
  last_triggered_at: Timestamp | null;
  note: string | null;
  params: Generated<Json>;
  repeat_mode: Generated<string>;
  saved_screen_id: string | null;
  status: Generated<string>;
  threshold: number | null;
  trigger_count: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
}

export interface AppAlertTrigger {
  alert_id: string;
  alert_version: number;
  id: Generated<number>;
  observed_value: number | null;
  payload: Generated<Json>;
  triggered_at: Generated<Timestamp>;
}

export interface AppConsent {
  granted: boolean;
  ip: string | null;
  notice_version: string;
  purpose: string;
  recorded_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppNote {
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  instrument_id: number | null;
  issuer_id: number | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppNotification {
  body: string;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  deeplink: string | null;
  id: Generated<string>;
  kind: string;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface AppNotificationDelivery {
  attempts: Generated<number>;
  channel: string;
  last_error: string | null;
  notification_id: string;
  provider_message_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AppPayment {
  amount_inr: Numeric;
  created_at: Generated<Timestamp>;
  gst_inr: Generated<Numeric>;
  id: Generated<string>;
  invoice_number: string | null;
  method: string | null;
  paid_at: Timestamp | null;
  provider_payment_id: string;
  status: string;
  subscription_id: string | null;
  user_id: string;
}

export interface AppPlan {
  billing_period: string;
  code: string;
  is_public: Generated<boolean>;
  limits: Json;
  name: string;
  price_inr: Generated<Numeric>;
}

export interface AppPortfolio {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppPortfolioTxn {
  charges: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  external_ref: string | null;
  id: Generated<string>;
  instrument_id: number;
  portfolio_id: string;
  price: Generated<Numeric>;
  quantity: Numeric;
  source: Generated<string>;
  trade_date: string;
  txn_type: string;
}

export interface AppPushSubscription {
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  keys: Json | null;
  last_used_at: Timestamp | null;
  platform: string;
  user_id: string;
}

export interface AppSavedPayoff {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  legs: Json;
  name: string;
  underlying_id: number;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppSavedScreen {
  columns: Generated<string[]>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_public: Generated<boolean>;
  last_result: ArrayType<number> | null;
  last_run_at: Timestamp | null;
  name: string;
  query_ast: Json;
  query_text: string;
  sort: Json | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppSession {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface AppSubscription {
  cancel_at_period_end: Generated<boolean>;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  id: Generated<string>;
  plan_code: string;
  provider: Generated<string>;
  provider_subscription_id: string | null;
  status: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppUsers {
  created_at: Generated<Timestamp>;
  email: string | null;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  image_url: string | null;
  is_anonymous: Generated<boolean>;
  last_seen_at: Timestamp | null;
  locale: Generated<string>;
  name: string | null;
  password_hash: string | null;
  phone_e164: string | null;
  phone_verified: Generated<boolean>;
  preferences: Generated<Json>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AppWatchlist {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  position: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppWatchlistItem {
  added_at: Generated<Timestamp>;
  instrument_id: number;
  position: number;
  watchlist_id: string;
}

export interface AppWebhookEvent {
  event_id: string;
  event_type: string;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
}

export interface CorpAnnouncement {
  attachment_key: string | null;
  attachment_url: string | null;
  body: string | null;
  category: string;
  dedupe_key: string | null;
  exchange_code: string;
  id: Generated<number>;
  issuer_id: number | null;
  published_at: Timestamp;
  search: Generated<string | null>;
  source_ref: string;
  subject: string;
  summary: string | null;
}

export interface CorpCreditRating {
  action: string | null;
  agency: string;
  id: Generated<number>;
  issuer_id: number;
  outlook: string | null;
  rated_on: string;
  rating: string;
  scale: string;
  security_id: number | null;
  source_url: string | null;
}

export interface CorpEvent {
  event_date: string;
  event_type: string;
  id: Generated<number>;
  issuer_id: number;
  purpose: string | null;
  source_ref: string | null;
  starts_at: Timestamp | null;
}

export interface CorpFinancialStatement {
  audited: boolean | null;
  consolidated: boolean;
  created_at: Generated<Timestamp>;
  filed_at: Timestamp | null;
  fiscal_period: number | null;
  fiscal_year: number;
  id: Generated<number>;
  is_latest: Generated<boolean>;
  issuer_id: number;
  period_end: string;
  period_type: CorpPeriodType;
  source: string;
  source_ref: string | null;
  statement: CorpStatementType;
  version: Generated<number>;
}

export interface CorpFinancialValue {
  item_code: string;
  statement_id: number;
  value: Numeric;
}

export interface CorpInsiderTrade {
  disclosed_on: string;
  holding_after_pct: Numeric | null;
  id: Generated<number>;
  mode: string | null;
  person_category: string;
  person_name: string;
  quantity: number;
  security_id: number;
  source: string;
  source_ref: string;
  txn_from: string | null;
  txn_to: string | null;
  txn_type: string;
  value_inr: Numeric | null;
}

export interface CorpLineItem {
  code: string;
  display_order: number;
  fs_format: Generated<string>;
  label: string;
  parent_code: string | null;
  statement: CorpStatementType;
  unit: Generated<string>;
}

export interface CorpMetricValue {
  consolidated: boolean;
  issuer_id: number;
  metric_code: string;
  period_end: string;
  period_type: CorpPeriodType;
  value: number | null;
}

export interface CorpNewsArticle {
  id: Generated<number>;
  lang: Generated<string>;
  published_at: Timestamp;
  snippet: string | null;
  source: string;
  title: string;
  url: string;
}

export interface CorpNewsMention {
  article_id: number;
  issuer_id: number;
  relevance: Generated<number>;
}

export interface CorpShareholding {
  category: string;
  holders: number | null;
  holding_pct: Numeric;
  period_end: string;
  pledged_pct: Numeric | null;
  security_id: number;
  shares: number | null;
}

export interface CorpValuationDaily {
  div_yield_pct: number | null;
  ev_ebitda: number | null;
  mcap_cr: number | null;
  pb: number | null;
  pe_ttm: number | null;
  security_id: number;
  trade_date: string;
}

export interface FiBond {
  coupon_frequency: number;
  coupon_rate_pct: Numeric | null;
  coupon_type: string;
  day_count: string;
  face_value: Numeric;
  floating_benchmark: string | null;
  is_callable: Generated<boolean>;
  is_puttable: Generated<boolean>;
  is_secured: boolean | null;
  is_tax_free: Generated<boolean>;
  issue_date: string | null;
  issue_size_inr: Numeric | null;
  maturity_date: string | null;
  min_investment_inr: Numeric | null;
  security_id: number;
  seniority: string | null;
  spread_bps: Numeric | null;
}

export interface FiCashflow {
  amount: Numeric;
  kind: string;
  pay_date: string;
  record_date: string | null;
  security_id: number;
}

export interface FiPriceDaily {
  clean_price: Numeric | null;
  security_id: number;
  trade_date: string;
  traded_fv_inr: Numeric | null;
  trades: number | null;
  venue: string;
  ytm_pct: Numeric | null;
}

export interface FiYieldCurvePoint {
  as_of: string;
  curve: string;
  tenor_years: Numeric;
  yield_pct: Numeric;
}

export interface IpoDocument {
  doc_type: string;
  filed_on: string | null;
  id: Generated<number>;
  issue_id: number;
  storage_key: string | null;
  url: string;
}

export interface IpoIssue {
  allotment_date: string | null;
  anchor_date: string | null;
  board: string;
  close_date: string | null;
  created_at: Generated<Timestamp>;
  demat_credit_date: string | null;
  employee_discount_inr: Numeric | null;
  exchanges: Generated<string[]>;
  face_value: Numeric | null;
  final_price: Numeric | null;
  fresh_issue_inr: Numeric | null;
  id: Generated<number>;
  issue_kind: Generated<string>;
  issuer_id: number;
  lead_managers: Generated<string[]>;
  listing_date: string | null;
  lot_size: number | null;
  ofs_inr: Numeric | null;
  open_date: string | null;
  price_band_high: Numeric | null;
  price_band_low: Numeric | null;
  pricing: string;
  refund_date: string | null;
  registrar: string | null;
  security_id: number | null;
  status: IpoStatus;
  total_issue_inr: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface IpoListing {
  close_price: Numeric | null;
  exchange_code: string;
  instrument_id: number | null;
  issue_id: number;
  listing_date: string;
  open_price: Numeric | null;
}

export interface IpoListingPerformance {
  close_price: Numeric | null;
  day1_close_gain_pct: Numeric | null;
  exchange_code: string | null;
  final_price: Numeric | null;
  issue_id: number | null;
  listing_date: string | null;
  listing_gain_pct: Numeric | null;
  open_price: Numeric | null;
}

export interface IpoReservation {
  category: string;
  issue_id: number;
  pct_of_issue: Numeric | null;
  shares: number | null;
}

export interface IpoSubscription {
  applications: number | null;
  captured_at: Timestamp;
  category: string;
  issue_id: number;
  shares_bid: number | null;
  shares_offered: number | null;
  times: Numeric | null;
}

export interface LabBacktestResult {
  benchmark: Json | null;
  equity_key: string | null;
  equity_sample: Json;
  metrics: Json;
  monthly_returns: Json;
  oos_from: string | null;
  run_id: string;
}

export interface LabBacktestRun {
  attempts: Generated<number>;
  bar_interval: string;
  cache_key: string;
  data_version: string;
  date_from: string;
  date_to: string;
  engine_version: string;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  initial_capital: Numeric;
  params: Generated<Json>;
  priority: Generated<number>;
  progress_pct: number | null;
  queued_at: Generated<Timestamp>;
  slippage_bps: Generated<Numeric>;
  started_at: Timestamp | null;
  status: Generated<LabRunStatus>;
  strategy_id: string;
  strategy_version: number;
  user_id: string;
  worker_id: string | null;
}

export interface LabBacktestTrade {
  charges: Generated<Numeric>;
  entry_at: Timestamp;
  entry_price: number;
  exit_at: Timestamp | null;
  exit_price: number | null;
  exit_reason: string | null;
  instrument_id: number;
  leg_no: Generated<number>;
  pnl: Numeric | null;
  quantity: Numeric;
  run_id: string;
  side: string;
  trade_no: number;
}

export interface LabJournalEntry {
  body: string;
  created_at: Generated<Timestamp>;
  entry_date: string;
  followed_plan: boolean | null;
  id: Generated<string>;
  instrument_id: number | null;
  order_id: string | null;
  plan_id: string | null;
  tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LabPaperAccount {
  cash: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  starting_capital: Numeric;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LabPaperDeployment {
  account_id: string;
  id: Generated<string>;
  params: Generated<Json>;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  stopped_at: Timestamp | null;
  strategy_id: string;
  strategy_version: number;
}

export interface LabPaperOrder {
  account_id: string;
  charges: Numeric | null;
  deployment_id: string | null;
  fill_price: number | null;
  filled_at: Timestamp | null;
  id: Generated<string>;
  instrument_id: number;
  limit_price: number | null;
  order_type: string;
  placed_at: Generated<Timestamp>;
  quantity: Numeric;
  reject_reason: string | null;
  side: string;
  status: Generated<string>;
  trigger_price: number | null;
}

export interface LabPaperPosition {
  account_id: string;
  avg_price: number;
  instrument_id: number;
  quantity: Numeric;
  realized_pnl: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface LabPlan {
  account_id: string | null;
  body: Json;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  name: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LabStrategy {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_archived: Generated<boolean>;
  latest_version: Generated<number>;
  name: string;
  style: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LabStrategyVersion {
  created_at: Generated<Timestamp>;
  definition: Json;
  strategy_id: string;
  version: number;
}

export interface MdBreadth1m {
  advances: number;
  declines: number;
  index_id: number;
  ts: Timestamp;
  unchanged: number;
}

export interface MdCandle15m {
  bucket: Timestamp | null;
  close: number | null;
  high: number | null;
  instrument_id: number | null;
  low: number | null;
  oi: number | null;
  open: number | null;
  turnover: number | null;
  volume: Numeric | null;
}

export interface MdCandle1d {
  close: number;
  delivery_pct: number | null;
  delivery_qty: number | null;
  high: number;
  instrument_id: number;
  last_price: number | null;
  low: number;
  oi: number | null;
  oi_change: number | null;
  open: number;
  prev_close: number | null;
  settle_price: number | null;
  source: Generated<string>;
  trade_date: string;
  trades: number | null;
  turnover: number | null;
  volume: Generated<number>;
}

export interface MdCandle1m {
  close: number;
  high: number;
  instrument_id: number;
  low: number;
  oi: number | null;
  open: number;
  ts: Timestamp;
  turnover: number | null;
  volume: Generated<number>;
}

export interface MdCandle5m {
  bucket: Timestamp | null;
  close: number | null;
  high: number | null;
  instrument_id: number | null;
  low: number | null;
  oi: number | null;
  open: number | null;
  turnover: number | null;
  volume: Numeric | null;
}

export interface MdFoChainSummary1m {
  atm_iv: number | null;
  atm_strike: number | null;
  ce_oi: number | null;
  ce_volume: number | null;
  expiry_date: string;
  forward_price: number | null;
  max_pain: number | null;
  pcr_oi: number | null;
  pcr_volume: number | null;
  pe_oi: number | null;
  pe_volume: number | null;
  skew_25d: number | null;
  ts: Timestamp;
  underlying_id: number;
  underlying_price: number | null;
}

export interface MdInstitutionalFlow {
  buy_value: Numeric;
  is_provisional: Generated<boolean>;
  net_value: Generated<Numeric | null>;
  participant: string;
  segment: string;
  sell_value: Numeric;
  trade_date: string;
}

export interface MdInstrumentDayStatus {
  band_pct: number | null;
  fut_eq_oi: number | null;
  in_fo_ban: Generated<boolean>;
  instrument_id: number;
  lower_circuit: number | null;
  mwpl_used_pct: number | null;
  surveillance: Generated<string[]>;
  trade_date: string;
  upper_circuit: number | null;
}

export interface MdLargeDeal {
  client_name: string;
  deal_type: string;
  id: Generated<number>;
  instrument_id: number;
  price: Numeric;
  quantity: number;
  side: string;
  trade_date: string;
}

export interface MdOptionEod {
  delta: number | null;
  gamma: number | null;
  instrument_id: number;
  iv: number | null;
  theta: number | null;
  trade_date: string;
  underlying_close: number | null;
  vega: number | null;
}

export interface MdParticipantOi {
  client_type: string;
  contract_group: string;
  long_contracts: number;
  short_contracts: number;
  trade_date: string;
}

export interface MfNav {
  nav: Numeric;
  nav_date: string;
  scheme_code: number;
}

export interface MfScheme {
  amc: string;
  amfi_category: string;
  asset_class: string;
  cagr_10y_pct: number | null;
  cagr_3y_pct: number | null;
  cagr_5y_pct: number | null;
  category: string;
  code: number;
  isin: string | null;
  launched_on: string | null;
  name: string;
  nav: Numeric | null;
  nav_date: string | null;
  return_1y_pct: number | null;
  updated_at: Generated<Timestamp>;
}

export interface OpsAuditLog {
  action: string;
  actor_id: string | null;
  actor_type: string;
  at: Generated<Timestamp>;
  details: Generated<Json>;
  id: Generated<number>;
  ip: string | null;
  target_id: string | null;
  target_type: string | null;
}

export interface OpsDataQualityIssue {
  business_date: string | null;
  check_name: string;
  details: Generated<Json>;
  detected_at: Generated<Timestamp>;
  id: Generated<number>;
  instrument_id: number | null;
  resolved_at: Timestamp | null;
  severity: string;
}

export interface OpsJobRun {
  attempt: Generated<number>;
  business_date: string;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<number>;
  job_name: string;
  meta: Generated<Json>;
  rows_written: number | null;
  started_at: Generated<Timestamp>;
  status: string;
}

export interface OpsSchemaMigration {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface RefChargeRate {
  basis: string;
  cap_inr: Numeric | null;
  component: string;
  exchange_code: string | null;
  id: Generated<number>;
  product: string;
  rate: Numeric;
  side: string;
  valid_during: string;
}

export interface RefCorporateAction {
  action_type: RefCorpActionType;
  announced_on: string | null;
  cash_per_share: Numeric | null;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  ex_date: string | null;
  id: Generated<number>;
  payment_date: string | null;
  ratio_new: Numeric | null;
  ratio_old: Numeric | null;
  record_date: string | null;
  security_id: number;
  source: string;
  source_ref: string;
}

export interface RefExchange {
  code: string;
  name: string;
  timezone: Generated<string>;
}

export interface RefIndexConstituent {
  index_id: number;
  member_id: number;
  valid_during: string;
  weight_pct: Numeric | null;
}

export interface RefIndustry {
  id: Generated<number>;
  level: number;
  name: string;
  parent_id: number | null;
  scheme: Generated<string>;
}

export interface RefInstrument {
  attrs: Generated<Json>;
  created_at: Generated<Timestamp>;
  delisted_on: string | null;
  display_name: string;
  exchange_code: string;
  expiry_date: string | null;
  id: Generated<number>;
  kind: RefInstrumentKind;
  listed_on: string | null;
  lot_size: Generated<number>;
  option_type: RefOptionType | null;
  price_multiplier: Generated<Numeric>;
  product: string | null;
  quote_unit: string | null;
  search_rank: Generated<number>;
  security_id: number | null;
  segment: RefSegment;
  series: string | null;
  session_group: Generated<string>;
  settlement_type: RefSettlementType | null;
  status: Generated<RefInstrumentStatus>;
  strike: Numeric | null;
  tick_size: Numeric;
  trading_symbol: string;
  underlying_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface RefInstrumentIdentifier {
  id: Generated<number>;
  id_type: string;
  id_value: string;
  instrument_id: number;
  valid_during: Generated<string>;
}

export interface RefIssuer {
  cin: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  fs_format: Generated<string>;
  id: Generated<number>;
  incorporated_on: string | null;
  industry_id: number | null;
  issuer_type: string;
  lei: string | null;
  name: string;
  short_name: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface RefPriceAdjustment {
  corporate_action_id: number | null;
  ex_date: string;
  kind: string;
  price_factor: number;
  security_id: number;
}

export interface RefSecurity {
  created_at: Generated<Timestamp>;
  face_value: Numeric | null;
  id: Generated<number>;
  isin: string | null;
  issuer_id: number;
  name: string;
  security_type: RefSecurityType;
  shares_outstanding: number | null;
  updated_at: Generated<Timestamp>;
}

export interface RefSecurityIsin {
  isin: string;
  security_id: number;
  valid_during: string;
}

export interface RefTradingDay {
  exchange_code: string;
  is_trading: boolean;
  note: string | null;
  segment: RefSegment;
  trade_date: string;
}

export interface RefTradingSession {
  ends_at: Timestamp;
  exchange_code: string;
  kind: RefSessionKind;
  segment: RefSegment;
  session_group: Generated<string>;
  starts_at: Timestamp;
  trade_date: string;
}

export interface ScrEquitySnapshot {
  atr_14: number | null;
  avg_turnover_20d_cr: number | null;
  avg_volume_20d: number | null;
  beta_1y: number | null;
  cagr_3y_pct: number | null;
  cagr_5y_pct: number | null;
  change_pct: number | null;
  current_ratio: number | null;
  debt_to_equity: number | null;
  delivery_pct_20d: number | null;
  dii_pct: number | null;
  div_yield_pct: number | null;
  ema_20: number | null;
  eod_updated_at: Timestamp | null;
  eps_ttm: number | null;
  ev_cr: number | null;
  ev_ebitda: number | null;
  fpi_pct: number | null;
  from_52w_high_pct: number | null;
  high_52w: number | null;
  index_ids: Generated<ArrayType<number>>;
  industry_id: number | null;
  instrument_id: number;
  interest_coverage: number | null;
  is_fo: Generated<boolean>;
  issuer_id: number;
  low_52w: number | null;
  macd_hist: number | null;
  mcap_bucket: string | null;
  mcap_cr: number | null;
  npm_pct: number | null;
  opm_pct: number | null;
  pb: number | null;
  pe_ttm: number | null;
  peg: number | null;
  price: number | null;
  price_updated_at: Timestamp | null;
  profit_cagr_3y_pct: number | null;
  profit_growth_yoy_pct: number | null;
  promoter_change_qoq: number | null;
  promoter_pct: number | null;
  promoter_pledge_pct: number | null;
  ps_ttm: number | null;
  return_1m_pct: number | null;
  return_1w_pct: number | null;
  return_1y_pct: number | null;
  return_3m_pct: number | null;
  roce_pct: number | null;
  roe_pct: number | null;
  rsi_14: number | null;
  sales_cagr_3y_pct: number | null;
  sales_growth_yoy_pct: number | null;
  security_id: number;
  sma_200: number | null;
  sma_50: number | null;
  volatility_1y_pct: number | null;
}

export interface ScrFoSnapshot {
  atm_iv: number | null;
  basis_pct: number | null;
  buildup: string | null;
  change_pct: number | null;
  expiry_date: string;
  fut_eq_oi: number | null;
  future_id: number | null;
  future_price: number | null;
  iv_rank_1y: number | null;
  max_pain: number | null;
  oi: number | null;
  oi_change_pct: number | null;
  pcr_oi: number | null;
  rollover_pct: number | null;
  underlying_id: number;
  updated_at: Generated<Timestamp>;
}

export interface ScrMetric {
  category: string;
  code: string;
  column_name: string;
  description: string | null;
  is_premium: Generated<boolean>;
  label: string;
  refresh: string;
  unit: string;
}

export interface DB {
  "app.alert": AppAlert;
  "app.alert_trigger": AppAlertTrigger;
  "app.consent": AppConsent;
  "app.note": AppNote;
  "app.notification": AppNotification;
  "app.notification_delivery": AppNotificationDelivery;
  "app.payment": AppPayment;
  "app.plan": AppPlan;
  "app.portfolio": AppPortfolio;
  "app.portfolio_txn": AppPortfolioTxn;
  "app.push_subscription": AppPushSubscription;
  "app.saved_payoff": AppSavedPayoff;
  "app.saved_screen": AppSavedScreen;
  "app.session": AppSession;
  "app.subscription": AppSubscription;
  "app.users": AppUsers;
  "app.watchlist": AppWatchlist;
  "app.watchlist_item": AppWatchlistItem;
  "app.webhook_event": AppWebhookEvent;
  "corp.announcement": CorpAnnouncement;
  "corp.credit_rating": CorpCreditRating;
  "corp.event": CorpEvent;
  "corp.financial_statement": CorpFinancialStatement;
  "corp.financial_value": CorpFinancialValue;
  "corp.insider_trade": CorpInsiderTrade;
  "corp.line_item": CorpLineItem;
  "corp.metric_value": CorpMetricValue;
  "corp.news_article": CorpNewsArticle;
  "corp.news_mention": CorpNewsMention;
  "corp.shareholding": CorpShareholding;
  "corp.valuation_daily": CorpValuationDaily;
  "fi.bond": FiBond;
  "fi.cashflow": FiCashflow;
  "fi.price_daily": FiPriceDaily;
  "fi.yield_curve_point": FiYieldCurvePoint;
  "ipo.document": IpoDocument;
  "ipo.issue": IpoIssue;
  "ipo.listing": IpoListing;
  "ipo.listing_performance": IpoListingPerformance;
  "ipo.reservation": IpoReservation;
  "ipo.subscription": IpoSubscription;
  "lab.backtest_result": LabBacktestResult;
  "lab.backtest_run": LabBacktestRun;
  "lab.backtest_trade": LabBacktestTrade;
  "lab.journal_entry": LabJournalEntry;
  "lab.paper_account": LabPaperAccount;
  "lab.paper_deployment": LabPaperDeployment;
  "lab.paper_order": LabPaperOrder;
  "lab.paper_position": LabPaperPosition;
  "lab.plan": LabPlan;
  "lab.strategy": LabStrategy;
  "lab.strategy_version": LabStrategyVersion;
  "md.breadth_1m": MdBreadth1m;
  "md.candle_15m": MdCandle15m;
  "md.candle_1d": MdCandle1d;
  "md.candle_1m": MdCandle1m;
  "md.candle_5m": MdCandle5m;
  "md.fo_chain_summary_1m": MdFoChainSummary1m;
  "md.institutional_flow": MdInstitutionalFlow;
  "md.instrument_day_status": MdInstrumentDayStatus;
  "md.large_deal": MdLargeDeal;
  "md.option_eod": MdOptionEod;
  "md.participant_oi": MdParticipantOi;
  "mf.nav": MfNav;
  "mf.scheme": MfScheme;
  "ops.audit_log": OpsAuditLog;
  "ops.data_quality_issue": OpsDataQualityIssue;
  "ops.job_run": OpsJobRun;
  "ops.schema_migration": OpsSchemaMigration;
  "ref.charge_rate": RefChargeRate;
  "ref.corporate_action": RefCorporateAction;
  "ref.exchange": RefExchange;
  "ref.index_constituent": RefIndexConstituent;
  "ref.industry": RefIndustry;
  "ref.instrument": RefInstrument;
  "ref.instrument_identifier": RefInstrumentIdentifier;
  "ref.issuer": RefIssuer;
  "ref.price_adjustment": RefPriceAdjustment;
  "ref.security": RefSecurity;
  "ref.security_isin": RefSecurityIsin;
  "ref.trading_day": RefTradingDay;
  "ref.trading_session": RefTradingSession;
  "scr.equity_snapshot": ScrEquitySnapshot;
  "scr.fo_snapshot": ScrFoSnapshot;
  "scr.metric": ScrMetric;
}
