/**
 * What each mutual fund category may hold, in a line: SEBI's rules for it,
 * plainly put. Durations are how long, on average, a debt fund's money is lent.
 */
export const CATEGORY_NOTES: Record<string, string> = {
  "Large cap": "At least 80% in the 100 largest companies.",
  "Large and mid cap": "At least 35% each in the 100 largest companies and the 150 after them.",
  "Mid cap": "At least 65% in the companies ranked 101st to 250th by size.",
  "Small cap": "At least 65% in companies smaller than the 250 largest.",
  "Multi cap": "At least 25% each in large, mid-sized and small companies.",
  "Flexi cap": "At least 65% in shares, of companies of any size, in whatever mix the manager picks.",
  Focused: "Shares of at most 30 companies.",
  "Value and contra": "Companies the market has marked down: bought for their value, or against the crowd.",
  "Dividend yield": "Mostly companies that pay out a large share of their profits.",
  "Tax saver (ELSS)": "Shares, locked in for three years. In the old tax regime, up to ₹1.5 lakh a year in them cuts taxable income.",
  "Sector and theme": "One sector or theme, such as banks, technology or infrastructure: more concentrated, more volatile.",
  "Equity index": "Follows an index, company for company, at a low cost.",
  "Debt index": "Follows a bond index, often holding its bonds until they mature.",
  "Aggressive hybrid": "65 to 80% in shares, the rest in bonds.",
  "Balanced advantage": "Moves between shares and bonds as markets rise and fall.",
  "Multi-asset": "At least 10% each in three kinds of asset, such as shares, bonds and gold.",
  "Equity savings": "Shares, bonds, and shares hedged with futures, for steadier returns.",
  "Conservative hybrid": "10 to 25% in shares, the rest in bonds.",
  "Balanced hybrid": "40 to 60% each in shares and bonds.",
  Arbitrage: "Buys shares and sells their futures to earn the gap: returns like cash, taxed like shares.",
  Overnight: "Lends for a day at a time.",
  Liquid: "Lends for up to 91 days.",
  "Money market": "Lends for up to a year, in money-market paper.",
  "Ultra short duration": "Lends for three to six months on average.",
  "Low duration": "Lends for six to twelve months on average.",
  "Short duration": "Lends for one to three years on average.",
  "Medium duration": "Lends for three to four years on average.",
  "Medium to long duration": "Lends for four to seven years on average.",
  "Long duration": "Lends for more than seven years on average: the most sensitive to interest rates.",
  "Dynamic bond": "Lends for as long or short as the manager thinks rates call for.",
  "Corporate bond": "At least 80% in companies' highest-rated bonds.",
  "Banking and PSU": "At least 80% in bonds of banks, public financial institutions and public sector companies.",
  "Credit risk": "At least 65% in bonds rated below the highest, for a higher yield and a higher risk of default.",
  Gilt: "At least 80% in government bonds: no risk of default, but sensitive to interest rates.",
  Floater: "At least 65% in bonds whose interest resets with market rates.",
  "Other debt": "Debt schemes that fit none of SEBI's categories.",
  Domestic: "Invests in other Indian mutual funds.",
  Overseas: "Invests in funds abroad, in foreign shares or bonds.",
  Retirement: "Locked in for five years or until retirement, whichever comes first.",
  Children: "Locked in for five years or until the child comes of age, whichever comes first.",
}
